// <auto-generated />
using System;
using healthcare_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace healthcare_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250919145218_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Healthcare_System.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Healthcare_System.Models.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BloodPressureDiastolic")
                        .HasColumnType("int");

                    b.Property<int?>("BloodPressureSystolic")
                        .HasColumnType("int");

                    b.Property<double?>("BodyMassIndex")
                        .HasColumnType("float");

                    b.Property<int?>("Cholesterol_HDL")
                        .HasColumnType("int");

                    b.Property<int?>("Cholesterol_Total")
                        .HasColumnType("int");

                    b.Property<bool?>("Condition_CardiovascularDisease")
                        .HasColumnType("bit");

                    b.Property<bool?>("Condition_DiabetesType1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Condition_DiabetesType2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Condition_FamilyHistoryHeartDisease")
                        .HasColumnType("bit");

                    b.Property<bool?>("Condition_Hyperlipidemia")
                        .HasColumnType("bit");

                    b.Property<bool?>("Condition_Hypertension")
                        .HasColumnType("bit");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ECG_Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FastingBloodSugar")
                        .HasColumnType("float");

                    b.Property<int?>("MajorVesselsColored")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientReportedDataJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int?>("RecordedByDoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("int");

                    b.Property<bool?>("Smoker")
                        .HasColumnType("bit");

                    b.Property<double?>("Smoker_PackYears")
                        .HasColumnType("float");

                    b.Property<int?>("Symptom_ChestPainType")
                        .HasColumnType("int");

                    b.Property<bool?>("Symptom_ExerciseInducedAngina")
                        .HasColumnType("bit");

                    b.Property<int?>("Symptom_ShortnessOfBreath")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RecordedByDoctorId");

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("Healthcare_System.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Healthcare_System.Models.MedicalHistory", b =>
                {
                    b.HasOne("Healthcare_System.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Healthcare_System.Models.Doctor", "RecordedByDoctor")
                        .WithMany()
                        .HasForeignKey("RecordedByDoctorId");

                    b.Navigation("Patient");

                    b.Navigation("RecordedByDoctor");
                });
#pragma warning restore 612, 618
        }
    }
}
